### ISSUE TITLE
Fix ptop py2 vs py3 issues

### ISSUE THREAD

**Issue by walles** [walles/px#17]
Try this on a mac:
* `./ci.sh`
* `./px.pex --top`

Expected result:
* Top running

Current result:
```
~/s/px (python|✔) $ ./px.pex --top

Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 339, in execute
  File ".bootstrap/_pex/pex.py", line 267, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 299, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 382, in _execute
  File ".bootstrap/_pex/pex.py", line 440, in execute_entry
  File ".bootstrap/_pex/pex.py", line 458, in execute_pkg_resources
  File "/Users/walles/.pex/install/px-1.0.1_9_gc554262-py2.py3-none-any.whl.633c18ceb49f98037fb9c2afce31a1399373e2ce/px-1.0.1_9_gc554262-py2.py3-none-any.whl/px/px.py", line 75, in main
    px_top.top()
  File "/Users/walles/.pex/install/px-1.0.1_9_gc554262-py2.py3-none-any.whl.633c18ceb49f98037fb9c2afce31a1399373e2ce/px-1.0.1_9_gc554262-py2.py3-none-any.whl/px/px_top.py", line 180, in top
    _top()
  File "/Users/walles/.pex/install/px-1.0.1_9_gc554262-py2.py3-none-any.whl.633c18ceb49f98037fb9c2afce31a1399373e2ce/px-1.0.1_9_gc554262-py2.py3-none-any.whl/px/px_top.py", line 144, in _top
    redraw(baseline, rows, columns)
  File "/Users/walles/.pex/install/px-1.0.1_9_gc554262-py2.py3-none-any.whl.633c18ceb49f98037fb9c2afce31a1399373e2ce/px-1.0.1_9_gc554262-py2.py3-none-any.whl/px/px_top.py", line 107, in redraw
    ordered = sorted(ordered, key=operator.attrgetter('cpu_time_seconds'), reverse=True)
TypeError: '<' not supported between instances of 'float' and 'NoneType'
~/s/px (python|✔) $
```

Workaround:
* `./ci.sh python`

**Comment by walles** [comment]
On the OSX machine where I got this problem there was no `python2` binary available.

Therefore `ci.sh` terminated after the first lap, and never got to doing the `python2` version.

The above error occurs when trying to run the `python3` built `px.pex` using Python 2.

Why that doesn't work I still don't know, but this at least shows how to repro the problem.

**Comment by walles** [comment]
Removing all `.pyc` file from `px.pex` does *not* resolve this.
