### ISSUE TITLE
Will not install with errors on Mac OSX HS

### ISSUE THREAD

**Issue by anika200** [walles/px#43]
Am I missing something here?
```
lee@Lees-iMac:~$ sudo -H pip install --upgrade pxpx
Password:
Collecting pxpx
  Downloading pxpx-1.0.11-py2.py3-none-any.whl
Collecting python-dateutil==2.6.1 (from pxpx)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.5MB/s 
Collecting docopt==0.6.2 (from pxpx)
  Downloading docopt-0.6.2.tar.gz
Collecting six>=1.5 (from python-dateutil==2.6.1->pxpx)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, docopt, pxpx
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-DJhpLh-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by anika200** [comment]
Hmmm, answering my own comment it looks like a permission error or some kind. New to Mac here from linux so some learnnig curve must be needed.

**Comment by walles** [comment]
You're trying to install globally, which apparently requires upgrading `six`.

On macOS, some files (like obviously the one you're accessing) are protected so that not even `root` can change them.

The easiest way to handle this is probably to use the install script instead:
```
curl -Ls https://github.com/walles/px/raw/python/install.sh | bash
```

Using the install script will only copy `px.pex` into `/usr/local/bin`, and thus dodge all the `pip` issues.

**Comment by anika200** [comment]
Thank you for the reply, I have since used this to install for me only.

`pip install --upgrade pxpx --user`

Arrr, now it says command not found when I type px. Hmmm, I already checked the path and it looks fine.

**Comment by walles** [comment]
Did you need to modify the `$PATH` after installation for this to work?

**Comment by anika200** [comment]
It seems I have the right path per your instructions.
```
lee@Lees-iMac:~$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Would I need to logout or anything odd on osx???

**Comment by walles** [comment]
After some Googling, it's apparently unclear where `--user` actually puts binaries on macOS.

I'd recommend the install script, it will install without fuss:
```
curl -Ls https://github.com/walles/px/raw/python/install.sh | bash
```

**Comment by anika200** [comment]
OK, working now with the script. Thank you. I appreciate your efforts.

**Comment by walles** [comment]
There's some help in https://github.com/pypa/pip/pull/4553, but at the time of me writing this that's waiting for a new release of Pip (newer than 9.0.1).

**Comment by walles** [comment]
I have just updated `README.md` to say that the script is the preferred way of installing, and that `pip install` can be problematic on macOS.

Thanks for reporting @anika200!
