### ISSUE TITLE
AttributeError: 'FakeProcess' object has no attribute 'command'

### ISSUE THREAD

**Issue by walles** [walles/px#54]
With 1.15:

```
2019-01-14T07:49:17.443104: Now invoking lsof, this can take over a minute on a big system...
2019-01-14T07:49:18.122760: lsof done, proceeding.
Traceback (most recent call last):
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 367, in execute
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 410, in _execute
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 468, in execute_entry
  File "/home/walles/px.pex/.bootstrap/_pex/pex.py", line 473, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px.py", line 104, in <module>
    main()
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px.py", line 84, in main
    px_processinfo.print_process_info(pid)
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px_processinfo.py", line 257, in print_process_info
    print_fds(process, processes)
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px_processinfo.py", line 182, in print_fds
    ipc_map = px_ipc_map.IpcMap(process, files, processes, is_root=is_root)
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px_ipc_map.py", line 60, in __init__
    self.fds = self._create_fds(is_root)
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px_ipc_map.py", line 131, in _create_fds
    str(target),
  File "/home/walles/.pex/install/pxpx-1.0.15-py2.py3-none-any.whl.8ceec020434f1407ad497e3388322d8868419814/pxpx-1.0.15-py2.py3-none-any.whl/px/px_process.py", line 78, in __str__
    return self.command + "(" + str(self.pid) + ")"
AttributeError: 'FakeProcess' object has no attribute 'command'
```

**Comment by walles** [comment]
Thinking out loud here, what must happen is that one of the things we depend upon is a `FakeProcess`.

That must have been created in `_create_mapping()`, either as "Running with sudo might help" or by  `_pid2process.get()` not returning any process.

Now, since we have code doing this, it should obviously work.

Plan:
1. Write a unit test triggering the first `FakeProcess` case and having that as a target.
2. Write a unit test triggering the second `FakeProcess` case and having that as a target.
3. Make sure both tests pass.

**Comment by walles** [comment]
The thing here is that `FakeProcess` needs to support `str()`.
