### ISSUE TITLE
Crash during ptop

### ISSUE THREAD

**Issue by walles** [walles/px#63]
My machine was slow without neither IO nor CPU load and behaving generally strange when this occurred with `ptop` 1.0.26:

```bash
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 352, in execute
  File ".bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File ".bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File ".bootstrap/pex/pex.py", line 397, in _execute
  File ".bootstrap/pex/pex.py", line 495, in execute_entry
  File ".bootstrap/pex/pex.py", line 502, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px.py", line 127, in <module>
    main()
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px.py", line 63, in main
    _main(sys.argv)
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px.py", line 88, in _main
    px_top.top()
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px_top.py", line 605, in top
    _top()
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px_top.py", line 578, in _top
    current = px_process.get_all()
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px_process.py", line 308, in get_all
    remove_process_and_descendants(processes, os.getpid())
  File "/Users/walles/.pex/install/pxpx-1.0.26-py2.py3-none-any.whl.1cce3bec393cb10b1a39d9ae68bd1dfd0859459c/pxpx-1.0.26-py2.py3-none-any.whl/px/px_process.py", line 288, in remove_process_and_descendants
    process = processes[pid]
KeyError: 18109
~/s/ghe-bridge (walles/python3|✚1) [1] $ px --version
1.0.26
~/s/ghe-bridge (walles/python3|✚1) $
```

**Comment by walles** [comment]
Fixed in cb6961d79cd88faae11681a4ea9618465197fca5.
