### ISSUE TITLE
ValueError: Logical must be >= physical, was: 1 (vs 6)

### ISSUE THREAD

**Issue by walles** [walles/px#78]
```
Problems detected, please send this text to one of:
* https://github.com/walles/px/issues/new
* johan.walles@gmail.com

Python version: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Platform info: Darwin-19.6.0-x86_64-i386-64bit

2020-08-19 07:59:23GMT ERROR    Running ptop failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px_top.py", line 570, in top
    _top()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px_top.py", line 515, in _top
    load_bar = px_load_bar.PxLoadBar(physical, logical)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px_load_bar.py", line 40, in __init__
    raise ValueError("Logical must be >= physical, was: %r (vs %r)" % (logical, physical))
ValueError: Logical must be >= physical, was: 1 (vs 6)
```

On this mac, I also did this:
```
$ sysctl hw|grep cpu:
hw.ncpu: 12
hw.activecpu: 12
hw.physicalcpu: 6
hw.logicalcpu: 12
$
```

From this, we should have gotten 12 logical (from `logicalcpu`), but got `1`.

Parsing is done in `px_cpuinfo.py`, `get_core_count_from_sysctl`.

**Comment by walles** [comment]
A `:` is missing on the line parsing `LOGICAL_PREFIX`, compare to how `PHYSICAL_PREFIX` is parsed.
