### ISSUE TITLE
px 1.0.37: Exception: Failed to match ps line

### ISSUE THREAD

**Issue by walles** [walles/px#81]
On macOS.

```
Traceback (most recent call last):
  File "/usr/local/bin/px", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px.py", line 76, in main
    _main(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px.py", line 174, in _main
    procs = filter(lambda p: p.match(arg), px_process.get_all())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px_process.py", line 365, in get_all
    process = ps_line_to_process(ps_line, now)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/px/px_process.py", line 288, in ps_line_to_process
    raise Exception("Failed to match ps line <%r>" % ps_line)
Exception: Failed to match ps line <'    1     0 Tis  1 Sep 06:56:38 2020         0   0,1   0:17.68  0,1 /sbin/launchd'>
```

**Comment by walles** [comment]
Output from `locale` on this machine:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_ALL=
```

**Comment by walles** [comment]
Either `LC_TIME` or `LC_NUMERIC` messes up `px`.

We should probably remove all `LC_` variables from the env before `exec`ing anything.

**Comment by walles** [comment]
Two things here:
1. `px` should report this error with the error reporting banner
2. `px` shouldn't break
