### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by walles** [walles/px#83]
Machine somewhat heavily loaded, `ps` might have provided inconsistent pids / ppids.

```
Problems detected, please send this text to one of:
* https://github.com/walles/px/issues/new
* johan.walles@gmail.com

Python version: 2.7.16 (default, Jun  5 2020, 22:59:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-

Platform info: Darwin-19.6.0-x86_64-i386-64bit

2020-12-16 18:05:53CET ERROR    Running ptop failed
Traceback (most recent call last):
  File "/Users/walles/.pex/install/pxpx-0.0.0-py2.py3-none-any.whl.f85a9198133c9a4092dbd2f8e1c6af0cf7583938/pxpx-0.0.0-py2.py3-none-any.whl/px/px_top.py", line 467, in top
    _top(search=search)
  File "/Users/walles/.pex/install/pxpx-0.0.0-py2.py3-none-any.whl.f85a9198133c9a4092dbd2f8e1c6af0cf7583938/pxpx-0.0.0-py2.py3-none-any.whl/px/px_top.py", line 454, in _top
    current = px_process.get_all()
  File "/Users/walles/.pex/install/pxpx-0.0.0-py2.py3-none-any.whl.f85a9198133c9a4092dbd2f8e1c6af0cf7583938/pxpx-0.0.0-py2.py3-none-any.whl/px/px_process.py", line 388, in get_all
    resolve_links(processes, now)
  File "/Users/walles/.pex/install/pxpx-0.0.0-py2.py3-none-any.whl.f85a9198133c9a4092dbd2f8e1c6af0cf7583938/pxpx-0.0.0-py2.py3-none-any.whl/px/px_process.py", line 364, in resolve_links
    process.parent = processes[process.ppid]
KeyError: 1397
```

```
$ px --version
1.2
$ 
```

**Comment by walles** [comment]
Maybe a dup of #34?
