### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by walles** [walles/px#84]
```
Problems detected, please send this text to one of:
* https://github.com/walles/px/issues/new
* johan.walles@gmail.com

px version: 1.4.0

Python version: 2.7.16 (default, Jun  5 2020, 22:59:21)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-

Platform info: Darwin-19.6.0-x86_64-i386-64bit

2021-02-18 11:34:04CET ERROR    Process age < 0: age_seconds=-0.643785 now=datetime.datetime(2021, 2, 18, 11, 34, 1, 356215, tzinfo=tzlocal()) start_time=datetime.datetime(2021, 2, 18, 11, 34, 2, tzinfo=tzlocal()) start_time_string=u'Thu Feb 18 11:34:02 2021' timezone='CET'
2021-02-18 11:34:04CET ERROR    Running ptop failed
Traceback (most recent call last):
  File "/usr/local/bin/ptop/px/px_top.py", line 481, in top
    _top(search=search)
  File "/usr/local/bin/ptop/px/px_top.py", line 468, in _top
    current = px_process.get_all()
  File "/usr/local/bin/ptop/px/px_process.py", line 442, in get_all
    process = ps_line_to_process(ps_line.decode('utf-8'), now)
  File "/usr/local/bin/ptop/px/px_process.py", line 346, in ps_line_to_process
    return process_builder.build(now)
  File "/usr/local/bin/ptop/px/px_process.py", line 284, in build
    cpu_time=self.cpu_time
  File "/usr/local/bin/ptop/px/px_process.py", line 116, in __init__
    assert False
AssertionError
```

**Comment by walles** [comment]
What if this is the cause?
Second 1: We look at the clock
Second 2: We talk to `ps`

Now, since we talk to `ps` *after* we look at the clock, the seconds hand could now have moved in between the clock check and the `ps` call.

**Comment by walles** [comment]
# Problematic code

https://github.com/walles/px/blob/5be71514095b558babf67372199d4176c35f020e/px/px_process.py#L109-L116
